Post http://localhost:3000/leads 

{
    "name" : "John cena",
    "email" : "john@cena.com", 
}

###
Post http://localhost:3000/leads 

Get http://localhost:3000/emailAccount/readEmail

Get http://localhost:3000/emailAccount/readEmail

###
Get http://localhost:3000/emailAccount/readEmail

###
Post http://localhost:3000/emailAccount/addEmail

{
    "name" : "john",
    "email" : "zephyrcreative4@gmail.com",
    "smtphost" : "mail.zephyrcreative.in",  
    "password" : "ayca6aw8habjwhb",  
    "port" : 857,  
    "secure" : true,  
}